[project]
name = "backend"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Salvador González", email = "zyrian@mylocker.dev"},
]
dependencies = ["ollama>=0.6.0", "fastapi>=0.118.2", "tortoise-orm>=0.25.1", "uvicorn>=0.37.0", "dotenv>=0.9.9", "pydantic-settings>=2.11.0", "asyncpg>=0.30.0", "aerich>=0.9.2"]
requires-python = "==3.14.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false

[dependency-groups]
dev = [
    "aerich>=0.9.2",
]

[tool.aerich]
tortoise_orm = "app.db.orm.TORTOISE_ORM"
location = "./migrations"
src_folder = "./."
